# Generated by Django 2.2 on 2021-10-20 07:36

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211020_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
