# Generated by Django 2.2 on 2021-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_directory_path', verbose_name='Picture'),
        ),
    ]
