# Generated by Django 2.2 on 2021-10-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='test_preview',
            new_name='text_preview',
        ),
    ]
